[DT-687] feat: Add support for reverse resolution
unstoppabledomains/resolution-service pull request #117
Opened 2022-06-02 01:06 UTC by DancingAxolotl

## Related story
https://linear.app/unstoppable-domains/issue/DT-687/support-reverse-resolution-in-resolution-service

## Changes
 - Added reverse resolution db model
 - Handled reverse resolution events in ETH worker
 - Added endpoints for reverse resolution
 - Upgraded uns lib version (contracts & sandbox)
 - Added migration to backfill reverse resolution records
 - Added tests

2022-06-16 04:19 UTC, sammyluo requested changes
Thanks for updating it! Exciting feature! 🙌 

It's a good start. Left some feedback.

2022-06-16 04:19 UTC, sammyluo commented on src/workers/eth/EthUpdater.ts
> +      where: { reverseAddress: addr.toLowerCase() },
We can set a transformer in the `reverseAddress` column in the `DomainsReverseResolution` table. Something like
```
  @Column('text', {transformer: lowercaseTransformer})
  reverseAddress: string;
```

2022-06-16 04:19 UTC, sammyluo commented on src/workers/eth/EthUpdater.ts
> +      where: { reverseAddress: addr.toLowerCase() },
Is it intentional that we don't need to specify the blockchain and network id here?

2022-06-16 04:19 UTC, sammyluo commented on src/workers/eth/EthUpdater.ts
> +              manager.getRepository(DomainsReverseResolution),
nit: why not having a variable just like `domainRepository` to be consistent?

```suggestion
              const domainReverseResolutionRepository = manager.getRepository(Domain);
              
              this.processRemoveReverse(
                event,
                domainReverseResolutionRepository,
              )
```

2022-06-17 13:09 UTC, DancingAxolotl commented on src/workers/eth/EthUpdater.ts
> +              manager.getRepository(DomainsReverseResolution),
I don't have any preference, but my reasoning to have it inline was that it's more compact this way.
It doesn't make sense to define it at the beginning of the function like `domainRepository` since it's only used here. 
And if someone ever needs to reuse this repository, they can add a variable where necessary.

If you think it's better to have a variable declared, I'll update it.

2022-06-17 21:40 UTC, sammyluo commented on src/workers/eth/EthUpdater.ts
> +              manager.getRepository(DomainsReverseResolution),
Make sense. No, I don't have strong preference here either. Let's leave it as it.

2022-06-21 22:24 UTC, sammyluo requested changes

2022-06-21 22:24 UTC, sammyluo commented on src/database/migrations/1654097320150-BackfillReverseResolutions.ts
> +          const domain = await Domain.findOne({ node: tokenId });
This is a N+1 query that could potentially affect the DB performance when this migration is running. We could optimize it so that once we get all the `events`, we query the list of corresponding domains right away, then processing them in-memory. Something like

```
const events = await queryRunner.manager.find(CnsRegistryEvent, {
  where: {
    type: ['SetReverse', 'RemoveReverse'],
  },
  order: {
    createdAt: 'ASC',
  },
});
const domainTokenIds = events
  .filter(({ type }) => type === 'SetReverse')
  .map(({ returnValues }) => returnValues.tokenId);

const domains = await Domain.find({ where: { node: In(domainTokenIds) } });
```

Then we can process and save the `DomainsReverseResolution` with `events` and `domains`

2022-06-21 22:24 UTC, sammyluo commented on src/models/DomainsReverseResolution.ts
> +  @Column('text', { transformer: lowercaseTransformer })
Sorry I should've explained it more clearly in my previous comment, but what I was envisioning was to have comments in the DB layer, something like
```suggestion
  @Column('text', { transformer: lowercaseTransformer, comment: 'unique index, the ethereum address that is configured for reverse resolution' })
```
so it would be beneficial for someone who operates the DB without checking the source code.

2022-06-21 22:24 UTC, sammyluo commented on src/models/Domain.test.ts
> +  describe('reverse resolution', () => {
Beautiful tests! 🙌

2022-06-22 12:30 UTC, DancingAxolotl commented on src/models/DomainsReverseResolution.ts
> +  @Column('text', { transformer: lowercaseTransformer })
Yes, This makes more sense. For some reason I assumed inline comments

2022-07-14 16:10 UTC, merged