Use ud asset mirror inside metadata service
unstoppabledomains/resolution-service pull request #131
Opened 2022-07-21 18:34 UTC by markvital

PFP NFT image should be cached on the side metadata service. 
After the event when 'social.picture.value' is changed on the blockchain and while putting in metadata service mirror, the picture should be retrieved and put in GCS CDN.
When the user retrieves image using '/image/:domainOrToken' or '/images-srt/:domainOrToken' we first check if the image is present in CDN and try to retrieve it.

### Related issue
https://linear.app/unstoppable-domains/issue/ECUX-276/use-ud-asset-mirror-inside-metadata-service

2022-07-25 15:29 UTC, iurevych requested changes
Feel free to re-request review whenever we can continue with QA. Currently uploads into GCP aren't working.

2022-08-03 13:51 UTC, DancingAxolotl commented on src/workers/eth/EthUpdater.ts
> +      await cacheSocialPictureInCDN(value, domain, resolution);
Should we also do it for the `ZilUpdater`?

2022-08-03 14:45 UTC, markvital commented on src/workers/eth/EthUpdater.ts
> +      await cacheSocialPictureInCDN(value, domain, resolution);
Sure, I'll add it!

2022-08-03 15:32 UTC, DancingAxolotl reviewed
Left a couple comments, but overall looks good. I will defer to ecomm team for final approval.

2022-08-03 15:32 UTC, DancingAxolotl commented on src/env.ts
> +        process.env.CLOUD_STORAGE_BUCKET_ID || 'resolution-client-assets',
I might be missing something but shouldn't there be an API key for uploading files to the cache?

2022-08-04 16:13 UTC, markvital commented on src/utils/socialPicture/index.ts
> +    return null;
If the image is not in CDN, we just show default placeholder for the domain.

For the old domains we'll do a migration separately, uploading images for all existent PFP NFT in CDN

2022-08-04 16:16 UTC, markvital commented on src/env.ts
> +        process.env.CLOUD_STORAGE_BUCKET_ID || 'resolution-client-assets',
Only bucket name. As I understood from talking to devOps team, the API key from GCS is stored somewhere else.

2022-08-04 16:18 UTC, markvital commented on src/workers/eth/EthUpdater.ts
> +      await cacheSocialPictureInCDN(value, domain, resolution);
Talked to Sergii, decided we won't be supporting Zil domains

2022-08-04 17:45 UTC, markvital commented
The tests that are failing are flaky: different test fails when I re-run the job. Ignoring them for now.
<img width="1089" alt="Screen Shot 2022-08-04 at 7 38 17 PM" src="https://user-images.githubusercontent.com/742796/182916325-0d8f9bf5-731b-4980-bf4f-31da6756a6a8.png">
<img width="805" alt="Screen Shot 2022-08-04 at 6 59 11 PM" src="https://user-images.githubusercontent.com/742796/182916344-450014ad-de1e-434d-8d46-9edba9bbd5e3.png">

2022-08-05 14:14 UTC, iurevych approved these changes
👍  awesome

2022-08-05 14:14 UTC, iurevych commented on src/utils/socialPicture/index.ts
> +  return `${nftPfpFolder}/${chainId}_${nftStandard}:${contractAddress}_${tokenId}_overlay.svg`;
We can combine `getNFTFilenameInCDN` and `getNFTFilenameWithOverlayInCDN` into one function

2022-08-05 14:14 UTC, iurevych commented on src/utils/socialPicture/index.ts
> +    .exists();
We can use `Promise.all` here to parallelise requests.

2022-08-05 14:14 UTC, iurevych commented on src/controllers/MetaDataController.ts
> +    const isSocialPictureVerified = socialPicture
```suggestion
    const isSocialPictureVerified = Boolean(socialPicture);
```

2022-08-05 14:16 UTC, iurevych commented
Release plan:
1. Upload historical NFT PFPs into GCP bucket
2. Release this PR

2022-08-05 14:28 UTC, iurevych commented
@DancingAxolotl can we by any chance run a similar script against production metadata service instance in order to populate cached images into our bucket?

``` ts
const resolutions = await DomainsResolution.find({where: ,...});
const domains = await ...;

for (const resolution of resolutions) {
  const domain = domains.find(d => resolutions.domainId === d.id);
  await cacheSocialPictureInCDN(resolution.resolution['social.picture.value'], domain, resolution);
}
```

2022-08-16 14:42 UTC, merged