Add avatars NFT PFP conversion from SVG to JPEG
unstoppabledomains/resolution-service pull request #137
Opened 2022-08-27 11:26 UTC by markvital

Implement SVG to PNG conversion using [convert-svg-to-jpeg](https://www.npmjs.com/package/convert-svg-to-jpeg) / [Puppeteer](https://github.com/puppeteer/puppeteer). SVG images would be used for twitter and open graph metadata for domain profiles.

After domain record social.picture.value is updated, we'll save 4 images in CDN:

- with overlay, SVG
- without overlay, SVG
- with overlay, JPG
- without overlay, JPG

2022-08-29 10:53 UTC, iurevych requested changes
Looks like this is what we'd want to test. Please see comments, we have to ensure requests are handled quickly.

2022-08-29 10:53 UTC, iurevych commented on src/utils/socialPicture/index.ts
> +  const fileNameWithOverlayJpeg = getNFTFilenameInCDN(socialPic, domain.name)?.replace('.svg', '.jpg');
Consider using `getNFTPictureFname`, it already does the replacement.

2022-08-29 10:53 UTC, iurevych commented on src/utils/socialPicture/index.ts
> +  const [fileWithOverlayJpegExists] = await bucket.file(fileNameWithOverlayJpeg).exists();
Consider parallelising requests:
```suggestion
  const [fileExists , fileWithOverlayExists, fileJpegExists, fileWithOverlayJpegExists] = await Promise.all([
    bucket.file(fileName).exists(),
    bucket.file(fileNameWithOverlay).exists(),
    bucket.file(fileNameJpeg).exists(),
    bucket.file(fileNameWithOverlayJpeg).exists()
  ]);
```

2022-08-29 10:53 UTC, iurevych commented on src/utils/socialPicture/index.ts
>        for (const file of files) {
Can we also run these requests in parallel?

2022-08-29 10:53 UTC, iurevych commented on src/utils/socialPicture/index.ts
> +  const [fileWithOverlayJpegExists] = await bucket.file(fileNameWithOverlayJpeg).exists();
Alternatively, have you tried this?
```ts
const files = await bucket.getFiles({
  prefix: fileName
});
```

You can extend `getNFTFilenameInCDN` to support an argument to return a file name without an extension.

2022-08-29 11:56 UTC, markvital commented on src/controllers/MetaDataController.ts
> +async function getOrCacheNowPfpNFTPath(
Because we need path to return path to redirect to the entry in the bucket and we need to return the binary of image (or string in case of SVG) in _/image/domain.x_ endpoint.
I actually didn't implement second use case properly yet. And we also have it in /metadata endpoint, where we embed the image in response (for the backward compatibility?)

2022-08-29 11:57 UTC, markvital commented on src/utils/socialPicture/index.ts
> +  const [fileWithOverlayJpegExists] = await bucket.file(fileNameWithOverlayJpeg).exists();
Let me try that..

2022-08-29 11:58 UTC, markvital commented on src/utils/socialPicture/index.ts
>        for (const file of files) {
Yes, of course

2022-08-29 15:53 UTC, markvital commented on src/utils/socialPicture/index.ts
> +  const fileNameWithOverlayJpeg = getNFTFilenameInCDN(socialPic, domain.name)?.replace('.svg', '.jpg');
Good eye, thank you

2022-09-13 14:53 UTC, mvlabat commented on Dockerfile
> +RUN yarn add @resvg/resvg-js-linux-arm64-musl --prefer-offline --frozen-lockfile --production --unsafe-perm --ignore-optional
I'm afraid this won't work for environments running on the arm64 architecture.

We should just remove the `--ignore-optional` flag from the command above.

2022-09-30 15:20 UTC, markvital commented on src/controllers/MetaDataController.ts
> +          rasterize
Reworked by introducing `PfpNftParams`
```javascript
async function getOrCacheNowPfpNFT(nftParams: PfpNftParams) {
  return getOrCacheImage(nftParams, getNftPfpImageFromCDN);
}
```

2022-09-30 15:26 UTC, mvlabat commented on Dockerfile
> +RUN yarn cache clean
this shouldn't be merged to master. Afaik, this error is present only in your local environment, but not in CI

2022-10-21 19:12 UTC, markvital commented
Continuing work on this in [PR#172](https://github.com/unstoppabledomains/resolution-service/pull/172)

2022-10-21 19:12 UTC, closed without merging