[SRE-647] enable datadog APM
unstoppabledomains/resolution-service pull request #146
Opened 2022-09-14 20:31 UTC by UDtorrey

2022-09-14 21:34 UTC, selfagency approved these changes
lgtm

2022-09-14 22:25 UTC, iurevych approved these changes
lgtm

2022-09-15 15:07 UTC, fruwe submitted a review, later dismissed
GAE environment variables need to be set here:
backend/backend-*.yaml

2022-09-15 15:44 UTC, sammyluo requested changes

2022-09-15 15:44 UTC, sammyluo commented on .github/workflows/deploy-production.yml
> +  DATADOG_AGENT_HOSTNAME: '10.128.0.31'
I think it's better to have it in `secrets` since this is a public repo, and there are partners hosting the service themselves.

2022-09-15 15:44 UTC, sammyluo commented on .github/workflows/deploy-staging.yml
> +  DATADOG_AGENT_HOSTNAME: '10.128.0.31'
I think it's better to have it in `secrets` since this is a public repo, and there are partners hosting the service themselves.

2022-09-15 15:44 UTC, sammyluo commented on src/env.ts
> +    DATADOG_APM_ENABLE: process.env.DATADOG_APM_ENABLE || true,
Should the default to be `true`?

2022-09-15 17:17 UTC, fruwe commented
My mistake, the env vars seem to get set in: `create-yaml.sh`
However, @sammyluo probably knows better how and where to set those variables, since this project is public

2022-09-15 18:17 UTC, UDtorrey commented on .github/workflows/deploy-production.yml
> +  DATADOG_AGENT_HOSTNAME: '10.128.0.31'
moved to GH secrets.

2022-09-15 18:17 UTC, UDtorrey commented on .github/workflows/deploy-staging.yml
> +  DATADOG_AGENT_HOSTNAME: '10.128.0.31'
move to GH secrets

2022-09-15 18:18 UTC, UDtorrey commented on src/env.ts
> +    DATADOG_APM_ENABLE: process.env.DATADOG_APM_ENABLE || true,
updated to 'false'

2022-09-15 18:37 UTC, sammyluo approved these changes
LGTM! 🚀 ⭐

2022-09-15 23:16 UTC, merged