Convert NFT PFT SVG to JPG using Puppeteer / Browserless
unstoppabledomains/resolution-service pull request #172
Opened 2022-10-21 18:48 UTC by markvital

In [PR#137](https://github.com/unstoppabledomains/resolution-service/pull/137) conversion of PFP avatars from SVG to JPG was implemented using 9convert-svg-to-jpeg](https://www.npmjs.com/package/convert-svg-to-jpeg) which is a very simple library, that startup Puppeteer locally.
Unfortunately, we were unable to start Puppeteer on GCS Compute Engine easily and decided to go with the SAAS solution instead.
Decided to go with [Browserless](https://www.browserless.io), which provides a robust production-ready wrapper around the Puppeteer providing a pool of warmed-up headless browsers instances and has a SAAS solution.

Here is how the conversion works locally. See README for details.

<img width="1177" alt="Screenshot 2022-10-21 at 20 36 03" src="https://user-images.githubusercontent.com/742796/197267570-b420e742-1fe7-41a9-b09c-460ca4d5f54e.png">

2022-10-24 13:14 UTC, DancingAxolotl requested changes
Looks good overall. 
Just a few questions for clarification

2022-10-24 13:14 UTC, DancingAxolotl commented on src/controllers/MetaDataController.ts
> +          socialPicture,
In the `/metadata/:domainOrToken` endpoint it looks like we use `getNftPfpImageFromCDN` instead of `getOrCacheNowPfpNFT` is there any reason to use one over the other? Should we use `getOrCacheNowPfpNFT` in the `/metadata` endpoint too?

Also, do you think we could remove the `image_data` field from the `/metadata` response entirely? If it has to generate an image it may cause high latency of the endpoint which may affect performance of the API. Since we already have the `image_url` there, is there a need to keep the image data in the response?

2022-10-24 13:14 UTC, DancingAxolotl commented on src/utils/socialPicture/index.ts
> +            const puppeteerURL = env.PUPPETEER.WS_URL || 'ws://localhost:3000';
Should we check if puppeteer is running during service startup?
Is it possible to make jpeg conversion optional?

2022-10-24 13:14 UTC, DancingAxolotl commented on local.dev.env.sample
> +PUPPETEER_WS=wss://chrome.browserless.io?token=094632bb-e326-4c63-b953-82b55700b14c
Are these real tokens? Is it okay to publish them?

2022-10-24 13:14 UTC, DancingAxolotl commented on README.md
> +where *token* is your API key
Do we need to replace the token with a placeholder?

2022-10-31 17:36 UTC, iurevych commented
Closing it since this project was deprioritised.

2022-10-31 17:36 UTC, closed without merging