[DT-937] feature: added generic rate limiting to routes
unstoppabledomains/resolution-service pull request #189
Opened 2022-11-07 21:59 UTC by DChan0319

## Background

Rate limiting is desired to reduce the abuse of public endpoints.

## Changes

Added rate limiter middleware to all controllers

## To Do

Load test 

## Additional Deployment and/or Rollback Steps

## Code Review

This Pull Request was thoroughly reviewed and meets all Code Review Standards pertaining to:

- [ ] **Implementation** - satisfied acceptance criteria
- [ ] **Communication** - notified engineers/stakeholders about impactful changes
- [ ] **Error handling** - handled, logged & alerted on errors
- [ ] **Documentation** - wrote readable code & commits, documented unintuitive code
- [ ] **Testing** - unit & E2E test coverage, tested in staging, DB migrations backwards compatible
- [ ] **Security** - sanitized inputs, vetted dependencies, validated/secured API requests, no committed secrets
- [ ] **Performance** - optimized expensive algorithms & database queries

Please select all **applied** standards relevant to this PR.
## Confirmation

- [ ] **Assignee Confirmation** - I (the author) have filled out the template above
- [ ] **Reviewer Confirmation** - I (a/the reviewer) confirm 1) the author has filled out the template and checked the box that says **Assignee Confirmation** 2) I reviewed the code and selected all applicable items in the code review section.

2022-11-10 03:14 UTC, sammyluo requested changes
Nice work! Left some minor change requests.

2022-11-10 03:14 UTC, sammyluo commented on src/env.ts
> +    },
```suggestion
    RATE_LIMITER: {
      DEFAULT_MAX_REQUESTS: parseNumberFromEnv(process.env.RATE_LIMITER_DEFAULT_MAX_REQUESTS, 5),,
      METADATA_MAX_REQUESTS: parseNumberFromEnv(process.env.RATE_LIMITER_METADATA_MAX_REQUESTS, 10),
      WINDOW_MS: parseNumberFromEnv(process.env.RATE_LIMITER_WINDOW_MS, 1000)
    },
```

2022-11-10 03:14 UTC, sammyluo commented on src/middleware/rateLimiter.ts
> +export default (options?: Partial<Options>): Handler => {
For the file name, let's use PascalCase to be consistent with other middleware.

2022-11-10 03:14 UTC, sammyluo commented on src/middleware/rateLimiter.ts
> +  if (process.env.NODE_ENV === 'test') {
What do you think of having an environment variable like `RATE_LIMITER_DISABLED` instead of detecting the `NODE_ENV` because sometimes the value of it is not very consistent or accurate?

2022-11-10 03:14 UTC, sammyluo commented on src/controllers/MetaDataController.ts
> +  rateLimiter({ max: env.APPLICATION.RATE_LIMITER.METADATA_NUMBER_REQUESTS }),
Nitpick: we can store the environment variable in a constant and put it at the beginning of the file, just like `BASE_IMAGE_URL`. The code would be cleaner.

2022-11-14 15:37 UTC, DChan0319 commented on src/controllers/DomainsController.ts
> +@UseBefore(ApiKeyAuthMiddleware, rateLimiter())
Not sure, but i don't think so. It was still working fine this way when i was testing.

2022-11-14 16:33 UTC, sammyluo commented on src/controllers/DomainsController.ts
> +@UseBefore(ApiKeyAuthMiddleware, rateLimiter())
Yeah, because the `ApiKeyAuthMiddleware` makes a DB query. If it goes through the rate limiter first, it could help save some resources.

2022-11-14 16:41 UTC, sammyluo commented on src/controllers/ReverseController.ts
> +@UseBefore(ApiKeyAuthMiddleware, RateLimiter())
Might wanna put RateLimiter() first here too.

2022-11-14 16:41 UTC, sammyluo commented on src/middleware/RateLimiter.ts
> +  if (process.env.RATE_LIMITER_DISABLED) {
Why not have it inside env.ts as well to centralize the config so it's easier to manage.

2022-11-14 20:09 UTC, sammyluo approved these changes
LGTM! 🚀 ⭐

2022-11-15 20:33 UTC, DChan0319 commented
Added the setting for the proxy: 
![image](https://user-images.githubusercontent.com/16522857/202019648-90519cb8-136a-4f0f-a0a0-e6f1eded658b.png)

2022-11-16 14:16 UTC, DancingAxolotl commented on src/env.ts
> +    },
@DChan0319 Could you add a short description of the new env. variables to the table in README.md? Also, are any of these required?

2022-11-16 15:19 UTC, DChan0319 commented on src/env.ts
> +    },
None are required and will defaulted to the 2nd parameter of parseNumberFromEnv() when not set in the env, but i'll add them to the table with a description.

2022-11-16 16:59 UTC, merged