[DT-926] Feature: Adding Heap tracking events in domain controller
unstoppabledomains/resolution-service pull request #200
Opened 2022-11-17 23:41 UTC by DChan0319

## Background

Want to start creating resolution service tracking events in order to determine who is using what endpoints.

## Changes

Included Heap tracking events in the domain controller.

## To Do

## Additional Deployment and/or Rollback Steps

## Code Review

This Pull Request was thoroughly reviewed and meets all Code Review Standards pertaining to:

- [ ] **Implementation** - satisfied acceptance criteria
- [ ] **Communication** - notified engineers/stakeholders about impactful changes
- [ ] **Error handling** - handled, logged & alerted on errors
- [ ] **Documentation** - wrote readable code & commits, documented unintuitive code
- [ ] **Testing** - unit & E2E test coverage, tested in staging, DB migrations backwards compatible
- [ ] **Security** - sanitized inputs, vetted dependencies, validated/secured API requests, no committed secrets
- [ ] **Performance** - optimized expensive algorithms & database queries

Please select all **applied** standards relevant to this PR.
## Confirmation

- [ ] **Assignee Confirmation** - I (the author) have filled out the template above
- [ ] **Reviewer Confirmation** - I (a/the reviewer) confirm 1) the author has filled out the template and checked the box that says **Assignee Confirmation** 2) I reviewed the code and selected all applicable items in the code review section.

2022-11-18 00:27 UTC, DChan0319 commented
![image](https://user-images.githubusercontent.com/16522857/202588673-6d1d13f4-ef2a-465d-bf17-a5c09b828689.png)

Tested the events coming through on staging. Just need to fix testing. Adding Heap broke the tests 😢

2022-11-18 21:27 UTC, sammyluo requested changes
Good start!

2022-11-18 21:27 UTC, sammyluo commented on src/types/heap.ts
> +  DOMAIN_VIEWED = 'ecbe - viewed - domain',
I don't know if want to do `viewed`?

2022-11-18 21:27 UTC, sammyluo commented on src/utils/heap.ts
> +  const response = await request({
Let's check if `app_id` is provided first. If not, it should do nothing. The reason is Heap should be pluggable, meaning if someone wants host their own server without Heap, they should be able to do it.

2022-11-21 17:55 UTC, markthepixel commented on src/types/heap.ts
> +  DOMAIN_VIEWED = 'ecbe - viewed - domain',
@unstoppable-allensun can weigh in here

2022-11-21 19:13 UTC, DChan0319 commented on src/types/heap.ts
> +  DOMAIN_VIEWED = 'ecbe - viewed - domain',
Changed it to this format: `rsbe - GET - domain`

2022-11-21 20:01 UTC, DChan0319 commented
<img width="841" alt="image" src="https://user-images.githubusercontent.com/16522857/203147646-349331b1-bcf5-4341-8028-df64957f4d83.png">
Updated to include URI & agreed upon naming convention.

2022-11-22 20:12 UTC, sammyluo requested changes

2022-11-22 20:12 UTC, sammyluo commented on src/controllers/DomainsController.ts
> +    await track({
I think we should avoid `await` here. It blocks the process and if the event fails to be tracked the whole request will fail. It's better to use non-blocking approach here with `.catch` to log the error with `logger`.

It's also better to move the tracking to the end of the controller before the `return`, so that if anything goes wrong with the business logic, we don't fire false positive tracking events.

Same comment for the other trackings.

2022-11-22 20:12 UTC, sammyluo commented on src/controllers/DomainsControllerGetRecords.test.ts
>    describe('GET /records', () => {
Let's add some tests to make sure heap tracking function is properly called when the controller is handling the request.

2022-11-23 19:23 UTC, sammyluo approved these changes
LGTM! Great work! 🚀 ⭐

2022-11-23 19:23 UTC, sammyluo commented on README.md
> +| HEAP_APP_ID | - | :x: | The application ID used for sending trackig events |
Let's mention it's Heap application ID, and maybe add a hyper link to https://www.heap.io/

2022-11-23 19:23 UTC, sammyluo commented on local.dev.env.sample
> +HEAP_APP_ID=developmentID
We can leave it as empty to avoid the tracking function being called. Otherwise it will throw a lot of errors during development

2022-11-23 19:23 UTC, sammyluo commented on local.test.env.sample
> +HEAP_APP_ID=developmentID
We can leave it as empty to avoid the tracking function being called. Otherwise it will throw a lot of errors during development

2022-11-23 19:23 UTC, sammyluo commented on src/controllers/DomainsController.ts
> +      track({
We can probably make it a function and call it whenever we need to avoid duplication

```suggestion
      const trackEvent = () => track({ ... });
      
      trackEvent();
```

2022-11-30 15:31 UTC, unstoppable-allensun commented on src/controllers/DomainsController.ts
> +      trackEvent();
If these are being called in all code paths in this function, why not just do it once at the top of the function? (instead of calling it three times)

2022-11-30 15:37 UTC, unstoppable-allensun commented on src/utils/heap.ts
> +export const normalizeHeapPropParam = (
Where is this being used?

2022-11-30 15:54 UTC, DChan0319 commented on src/types/heap.ts
> +  GET_DOMAIN = 'rsbe - GET - domain',
yes, not a problem!

2022-11-30 15:57 UTC, DChan0319 commented on src/utils/heap.ts
> +export const normalizeHeapPropParam = (
No where right now, i just wanted to have this ready to be used in the future, we are going to have POST requests. https://linear.app/unstoppable-domains/issue/DT-962/bulk-reverse-endpoint-on-resolution-service <-- is an example. We could probably use this function for the list of addresses that are being provided.

2022-11-30 17:49 UTC, unstoppable-allensun commented on src/utils/heap.ts
> +export const normalizeHeapPropParam = (
Sounds good! Thanks for the info.

2022-11-30 17:55 UTC, DChan0319 commented on src/controllers/DomainsController.ts
> +      trackEvent();
I think if the endpoint were to fail somewhere in between any of the logic it would still send a heap event somewhere regardless of the if statements, but the refactor is much cleaner anyways hahaha

2022-11-30 17:57 UTC, DChan0319 commented on src/utils/heap.ts
> +export const normalizeHeapPropParam = (
This can also be used for any GET request query params that are lists that we want to have an easier access to. instead of parsing the uri if it gets too long. There have been some partners that have been sending really long GET requests to search a butt load of things that would hit the character limit.... so even the uri custom param may need to be "broken up"

2022-12-01 03:43 UTC, sammyluo approved these changes
Beautiful! 🚀 ⭐

2022-12-01 15:39 UTC, MaximusMcCann commented on src/middleware/SendHeapEvent.ts
> +      case EHttpMethods.GET:
For what it's worth, as an engineer on another team, I don't know what an `EHttpMethods`.  E for event?  Just food for thought as UD grows and we have more new engineers looking at code :)

2022-12-01 15:42 UTC, MaximusMcCann commented on src/types/common.ts
> +export enum EHttpMethods {
```suggestion
export enum EventHttpMethods {
```

Maybe just spell it out, unless `E` doesn't actually stand for `Event` 😬 .
Or `TrackingEventHttpMethods` or `HeapHttpMethods` 🤷🏻‍♂

2022-12-01 15:44 UTC, MaximusMcCann commented on src/utils/heap.ts
> +  }
@unstoppable-allensun Here they've decided to straight truncate.  Thoughts?  I believe we decided to not convert the json to a truncated string, no?

2022-12-01 15:53 UTC, unstoppable-allensun commented on src/utils/heap.ts
> +  }
Yah he said this was not being used anyways currently when I asked about this method.  This isn't truncating json though. It's converting arrays into comma separated list and truncating that. For that we could add "..." to the end to indicate it was truncated and then log that data was truncated.

2022-12-01 16:16 UTC, DChan0319 commented on src/middleware/SendHeapEvent.ts
> +      case EHttpMethods.GET:
E stands for Enum and I for Interface. When importing a type, i rather have some sort of indication as to what custom type, interface, or enum was created, right now it's not clear what i'm importing from the different files, i'd have to check and make sure in the type declaration with this i know I'm going to import and enum vs an interface or type. Totally fine and happy to remove though. Just thought it would be even clearer as a standard to our type definitions if introduced.

2022-12-01 16:20 UTC, DChan0319 commented on src/types/common.ts
> +export enum EHttpMethods {
Doesnt stand for Event. Stands for Enum HttpMethods, when importing it has a clear indication that these are enums vs an Interface. I could have an Interface with the same name and same description. EHttpMethods as this enum with the strings and an interface as IHttpMethods as another declared custom type.

2022-12-01 16:45 UTC, MaximusMcCann commented on src/utils/heap.ts
> +  }
oh 🤦🏻

2022-12-01 16:48 UTC, MaximusMcCann commented on src/types/common.ts
> +export enum EHttpMethods {
Gotcha.  More common practice would be to just have a singular Enum them,  so `HttpMethod`

2022-12-01 16:58 UTC, MaximusMcCann commented on src/utils/heap.ts
> +      }
We should throw a log if it goes over and have the log include the entire `property`

2022-12-01 23:32 UTC, merged