Add clean attribute type
unstoppabledomains/resolution-service pull request #205
Opened 2022-11-23 03:42 UTC by sudoryan

Adds clean attribute type

2022-11-25 05:02 UTC, sammyluo requested changes
Good start! Left a change request.

2022-11-25 05:02 UTC, sammyluo commented on src/models/Domain.ts
> +    return repository.count({
If the purpose is to figure out if a domain has a child so that we can determine if it has subdomain or not, then it's better to use `findOne` instead of `count` for better performance. We should also add caching on it using the `cache` option in TypeORM.

2022-11-25 05:02 UTC, sammyluo commented on src/utils/metadata/index.ts
> +  Clean = 'clean', // domain has no subdomains
Just curious if "clean" is a good naming to represent a domain has no subdomain? 🤔

2022-11-27 19:55 UTC, sudoryan commented on src/utils/metadata/index.ts
> +  Clean = 'clean', // domain has no subdomains
It was suggested by Matt G. and intended to identify domains that are eligible for returns. The original suggestion was "clean (no subdomains)" 😅

2022-11-29 09:05 UTC, iurevych commented
@sudoryan should we add the new attribute type without modifying the default standard type? This is to avoid OpenSea caching issue where after this change all tokens will keep showing stale metadata (standard not clean type).

I'd propose adding a new type `WithSubdomains` if the domain has subdomains. This way as subdomains gain more popularity we'll start seeing this new trait becoming visible at OpenSea.

2022-12-08 16:55 UTC, closed without merging