[DT-936] Added typeorm in memory cache to all GET requests DB queries
unstoppabledomains/resolution-service pull request #210
Opened 2022-11-29 21:24 UTC by DChan0319

## Background

We want to implement some basic forms of caching first in order to improve response times for the resolution service. 

## Changes

Added typeorm in memory caching implementation for all GET requests utilizing DB queries.

## To Do

## Additional Deployment and/or Rollback Steps

## Code Review

This Pull Request was thoroughly reviewed and meets all Code Review Standards pertaining to:

- [ ] **Implementation** - satisfied acceptance criteria
- [ ] **Communication** - notified engineers/stakeholders about impactful changes
- [ ] **Error handling** - handled, logged & alerted on errors
- [ ] **Documentation** - wrote readable code & commits, documented unintuitive code
- [ ] **Testing** - unit & E2E test coverage, tested in staging, DB migrations backwards compatible
- [ ] **Security** - sanitized inputs, vetted dependencies, validated/secured API requests, no committed secrets
- [ ] **Performance** - optimized expensive algorithms & database queries

Please select all **applied** standards relevant to this PR.
## Confirmation

- [ ] **Assignee Confirmation** - I (the author) have filled out the template above
- [ ] **Reviewer Confirmation** - I (a/the reviewer) confirm 1) the author has filled out the template and checked the box that says **Assignee Confirmation** 2) I reviewed the code and selected all applicable items in the code review section.

2022-12-01 04:18 UTC, sammyluo requested changes
Great start! Left some minor change requests.

2022-12-01 04:18 UTC, sammyluo commented on src/controllers/DomainsController.ts
> +      .cache(env.CACHE.IN_MEMORY_CACHE_EXPIRATION_TIME)
What happens if `IN_MEMORY_CACHE_DISABLED` is set to `false`? Is it still going to be cached but not using in-memory caching mechanism?

2022-12-01 04:18 UTC, sammyluo commented on src/controllers/DomainsController.ts
> +    const lastTransferEvents = await domainEvents
Sorry, I should've clarified in the story, but I think this one would be an exception since it's supposed to return the latest blockchain events, so we should return real-time data.

2022-12-01 04:18 UTC, sammyluo commented on src/database/connect.ts
> +    ...(!env.CACHE.IN_MEMORY_CACHE_DISABLED && {
Any reason we need to define the cache provider here again if it's ready in ormconfig.ts?

2022-12-01 04:18 UTC, sammyluo commented on src/models/Domain.ts
> +    cache?: boolean,
I don't think we should provide a cache option for find or build operation. Imagine if some code that looks up the domain first and it doesn't exist, then it returns a new Domain instance and persisted into the DB. Then if a function looks up the same data within 10 mins, it will hit the cache and still say that the domain doesn't exist.

2022-12-01 20:44 UTC, DChan0319 commented on src/database/connect.ts
> +    ...(!env.CACHE.IN_MEMORY_CACHE_DISABLED && {
When i was running the tests locally, I wasn't seeing the caching actually taking place, but the caching was throwing errors when I added it here. My question i guess is when or how does this config get used or read?

2022-12-01 20:54 UTC, DChan0319 commented on src/controllers/DomainsController.ts
> +      .cache(env.CACHE.IN_MEMORY_CACHE_EXPIRATION_TIME)
If caching is not disabled, many of the unit tests were failing. As soon as i disabled the cache, the unit tests pass. So, to me that meant, if caching is disabled, everywhere were we see `.cache()` format of code doesn't actually take place unless in the config it is provided. The only place where test results were being cached and being affected was when i enabled caching in the connect.ts file.

2022-12-01 20:57 UTC, DChan0319 commented on src/database/connect.ts
> +    ...(!env.CACHE.IN_MEMORY_CACHE_DISABLED && {
The only place i see ormconfig.ts being referenced is in the tsconfig.json file.. so i dont think it's even being used other than being scanned for typescript.

2022-12-01 20:59 UTC, sammyluo commented on src/database/connect.ts
> +    ...(!env.CACHE.IN_MEMORY_CACHE_DISABLED && {
It should be picked up by TypeORM automatically

2022-12-01 21:50 UTC, DChan0319 commented on src/database/connect.ts
> +    ...(!env.CACHE.IN_MEMORY_CACHE_DISABLED && {
ah, okay i see `ts-node` in the scripts allows for this. I'll remove it here then. I don't think we even need the env.CACHE.IN_MEMORY_CACHE_DISABLED environment variable then either cause it was only introduced for testing and testing doesn't need this if i remove this logic.

2022-12-01 21:53 UTC, DChan0319 commented on src/controllers/DomainsController.ts
> +      .cache(env.CACHE.IN_MEMORY_CACHE_EXPIRATION_TIME)
In the revision, the cache should never be disabled. I only introduced the flag because i thought i needed to turn it off for tests.

2022-12-02 02:58 UTC, sammyluo approved these changes
Great work! 🚀 ⭐

2022-12-02 02:58 UTC, sammyluo commented on src/models/Domain.ts
> +      cache: cache ? env.CACHE.IN_MEMORY_CACHE_EXPIRATION_TIME : undefined,
Same comment as find or create operation - we shouldn't provide cache option.

2022-12-02 02:58 UTC, sammyluo commented on src/database/connect.ts
> +import InMemoryCacheProvider from './TypeormInMemoryCache';
Unused variable.

2022-12-02 03:08 UTC, merged