[API-406] [WIP] resolution api latency tweaks
unstoppabledomains/resolution-service pull request #308
Opened 2023-03-20 08:49 UTC by DancingAxolotl

## Background

Some minor tweaks to improve resolution service API p99 latency and latency spikes.

## Changes

 - Made API docs (swagger) into a separate running mode to improve startup latency for metadata API
 - Changed default running mode for `*-meta` instances to `METADATA_API`
 - Changed `/status` endpoint to use time since last update for status instead of block height to remove external queries
 - Tweaked `/metadat` endpoint:
  -- Removed `count` for subdomains - use relation instead
  -- Batch DB queries internally to save postgres connections under high N of concurrent requests 
  -- Removed on-chain lookup for missing domains

## To Do

 - [] test to make sure everything works
 - [] clean up db query batching, make sure that 
 - [] set up secrets for new status timeouts, come up with reasonable estimates for these values (currently all set to 5 min)

## Code Review

This Pull Request was thoroughly reviewed and meets all Code Review Standards pertaining to:

- [ ] **Implementation** - satisfied acceptance criteria
- [ ] **Communication** - notified engineers/stakeholders about impactful changes
- [ ] **Error handling** - handled, logged & alerted on errors
- [ ] **Documentation** - wrote readable code & commits, documented unintuitive code
- [ ] **Testing** - unit & E2E test coverage, tested in staging, DB migrations backwards compatible
- [ ] **Security** - sanitized inputs, vetted dependencies, validated/secured API requests, no committed secrets
- [ ] **Performance** - optimized expensive algorithms & database queries

Please select all **applied** standards relevant to this PR.
## Confirmation

- [ ] **Assignee Confirmation** - I (the author) have filled out the template above
- [ ] **Reviewer Confirmation** - I (a/the reviewer) confirm 1) the author has filled out the template and checked the box that says **Assignee Confirmation** 2) I reviewed the code and selected all applicable items in the code review section.

2023-03-20 15:48 UTC, DancingAxolotl commented on src/services/DomainService.ts
> +  const finalDomain = domain || znsDomain; // || await Domain.findOnChainNoSafe(tokenName);
@sammyluo I think we discussed it before, but I'd like to bring it up again, `findOnChainNoSafe` is probably unnecessary here since we greatly reduced confirmation times for all chains. It also allows for DDoS attacks by spamming known non-existing token IDs (0, 1, 2, 3, etc.). So I think it would be better to drop it entirely.

However, keeping it is still an option if we need to. It will increase our average latency, but the main bottleneck was postgres connections so we should be okay.

2023-03-20 16:15 UTC, DancingAxolotl commented on src/services/DomainService.ts
> +  });
Yes, normally you would need some synchronization to avoid situations like that. Thankfully, node.js is single-threaded. So that shouldn't be an issue.

Letting Node decide would be great, but the issue is typeorm which has a limited number of connections to the DB (10 currently). When we have, for example, 80 incoming requests at the same time, the first 10 will get their DB connections, while the rest 70 will be stuck waiting in the typeorm queue. At the same time another 80 requests will come in. So the total queue just keeps growing, resulting in huge latencies.

This way we let all 80 requests "push" their DB queries without eating up postgres connections. Once all incoming requests are handled, we can make a single DB query and return results to be handled on the next iteration of the event loop.

2023-03-20 18:28 UTC, tunguyennnnn commented on src/services/DomainService.ts
> +  });
what's this trying to do is trying to mimic a batch load pattern which is very common in graphql. I feel like we need to introduce proper interface or use existing library that already use this for better abstraction otherwise it will be hard to debug 
Have you looked into libraries such as this https://www.npmjs.com/package/batchloader to see if it can achieve what you need? (the `load` method  is the one that will perform query to DB in 1 tick)

or if you want to build your own this is a good reference.https://github.com/graphql/dataloader in https://github.com/graphql/dataloader/blob/main/src/index.js, it's somewhat similar to what you try to achive except that the assumption of the lib is queries are batched within 1 tick of the even loop. But regardless, it offers APIs batch load functions

2023-03-20 18:33 UTC, tunguyennnnn commented on src/services/DomainService.ts
> +  });
and since it operates on the assumption of 10 connections in the pools, it should be configurable on how much time per batch, how many items per batch.

2023-03-20 18:52 UTC, DancingAxolotl commented on src/services/DomainService.ts
> +  });
Oh, nice find @tunguyennnnn !!!
I was looking for a library like this, but for some reason I couldn't find it :)
It seems to do the same thing as my little implementation except with a `setTimeout` instead of `setImmediate` but ultimately it should have the same effect. I'll try it here. Thanks!

2023-03-21 09:45 UTC, DancingAxolotl commented on src/services/DomainService.ts
> +  });
`batchloader` worked. Thanks everyone!

2023-03-21 11:02 UTC, tunguyennnnn commented on src/services/DomainService.ts
> +  });
awesome!

2023-03-21 20:19 UTC, anhan32 reviewed
looks ok to me but defer @sammyluo @tirish @tunguyennnnn for approval

2023-03-21 20:19 UTC, anhan32 commented on src/services/DomainService.ts
> +  200,
can you add comments to what these inputs correlate too? does this configuration essentially mean "for each loop, batch 200 requests"?

2023-03-21 20:54 UTC, sammyluo requested changes

2023-03-21 20:54 UTC, sammyluo commented on package.json
> +    "batchloader": "^0.0.22",
I'm not sure about this package. Last published was 3 years ago so it seems like it's no longer being mainstream. Do you know any other alternatives?

2023-03-21 20:54 UTC, sammyluo commented on src/api.ts
> +  env.APPLICATION.RUNNING_MODE.includes('API_DOCS')
Please rebase as you don't need this anymore

2023-03-21 20:54 UTC, sammyluo commented on src/controllers/StatusController.ts
> +    const lastUpdated = workerStatus?.updatedAt?.getTime() || 0;
Not a problem now, but using the table `updatedAt` field might not correctly reflect the last successfully synced time, especially if we are expanding the table to keep track of other fields in the future, this will be a bug.

2023-03-21 20:54 UTC, sammyluo commented on src/services/DomainService.ts
> +  const supportedTLD = finalDomain ? isSupportedTLD(finalDomain.name) : false;
Now that you are here, we can even have another `isSupportedTLD` at the beginning of the function to do a simple check first. If it's not supported, then no need to query at all.

2023-03-21 20:54 UTC, sammyluo commented on src/services/MetadataService.ts
> -        value: await Domain.getSubdomainCountByParentName(domain.name),
Might as well just delete the function `getSubdomainCountByParentName()` implementation?

2023-03-22 12:18 UTC, DancingAxolotl commented on package.json
> +    "batchloader": "^0.0.22",
Originally I planned to implement this myself. @tunguyennnnn found this package and it seems to do the same thing.
It is a pretty simple utility, so it makes sense that it's not updated very often.
There is https://github.com/graphql/dataloader which seems to be updated more often, but I'm not sure if it will work the same way. I'll take a look.

2023-03-22 12:20 UTC, DancingAxolotl commented on src/controllers/MetaDataController.test.ts
> +    it.skip('should query the newURI event on the fly to return a freshly minted domain', async () => {
I'll remove it completely if we decide to remove the "on the fly" fetching. See this comment:
https://github.com/unstoppabledomains/resolution-service/pull/308#discussion_r1142335677

2023-03-22 13:14 UTC, tunguyennnnn commented on package.json
> +    "batchloader": "^0.0.22",
yea i don't remember https://github.com/graphql/dataloader was updated that often when I first saw it few years ago 😄.  but yea I'd not expect this package to be updated often. 

@sammyluo has a point that this package has only 36 stars on github, we can try to read through the code to see if it does what we need

2023-03-22 16:00 UTC, DancingAxolotl commented on src/services/DomainService.ts
> +  const supportedTLD = finalDomain ? isSupportedTLD(finalDomain.name) : false;
We need to find the domain before checking this in case we get a token id as input. If we only check in the beginning we will not catch unsupported token ids.

2023-03-22 16:12 UTC, DancingAxolotl commented on package.json
> +    "batchloader": "^0.0.22",
Looks like `dataloader` is a bit more advanced. I was able to replace `batchloader` with it, just need to test to make sure that it works the same.

2023-03-22 16:19 UTC, tunguyennnnn commented on package.json
> +    "batchloader": "^0.0.22",
yea i wouldn't use `dataloader`, it's specific to graphql to batch resolvers query within a single tick of the event loop. I just mentioned it as I was surprised that it's got maintained often because the original implementation was pretty niche already. `batchloader` is more for generic usage like ours

2023-03-22 16:23 UTC, DancingAxolotl commented on src/api.ts
> +  env.APPLICATION.RUNNING_MODE.includes('API_DOCS')
I left the env variable to allow us to disable swagger generation entirely to improve startup latency. For example, the metadata API does not need it, so we can save some time on startup.

2023-03-22 16:41 UTC, tunguyennnnn commented on src/controllers/StatusController.ts
> +    const lastUpdated = workerStatus?.updatedAt?.getTime() || 0;
yea I wonder how much this would save us for not fetching from providers. We don't have much traffic for this endpoint

2023-03-22 16:50 UTC, tunguyennnnn commented on src/services/DomainService.ts
> +    batchScheduleFn: setImmediate,
🤔 i am not sure about this. have you test actual batch size with using `setImmediate`, I think it would just execute immediately per request because each api requests coming will make load function executed immediately

2023-03-22 16:55 UTC, tunguyennnnn commented on src/services/DomainService.ts
> +  const [domain, znsDomain] = await domainsBatchLoader.loadMany([
It's good start, I won't block PR for this comment but It's better if we like a DomainRepository with API of findMany wrapping the batcher. Service should not care how data is being fetched.

2023-03-22 17:49 UTC, tirish commented on src/api.ts
> +  });
Minor: can keep this part out of the conditional

2023-03-22 17:49 UTC, tirish commented on src/api.ts
> +  api.get('/_status', (_: Request, res: Response) => {
Should this be conditional?

2023-03-22 17:49 UTC, tirish commented on src/env.ts
> +  | 'API_DOCS';
Minor: the `_DOCS` part is a bit misleading now that doc hosting is removed, maybe `_SCHEMA` or `_SPEC`? 🤷

2023-03-22 17:49 UTC, tirish commented on src/services/MetadataService.ts
> +        value: domain.children?.length || 0,
I see you added `children` to the `relations`, should we load the hydrated subdomain list every time?

2023-03-22 19:19 UTC, tunguyennnnn commented on src/services/DomainService.ts
> +    batchScheduleFn: setImmediate,
yes `setImmediate` will call in the next tick, but i was wondering is it enough time to accumulate domains from other requests. I was thinking of setTimeout(0) but an actually time out of 100 ms for example. 
if you look at this. it's actually the promise queue in the middle will be exhausted right after the any of the `timeout`, `callback`, `setimmediate` get called
sorry about the picture 🥲 but it's the only one I found where there's an arrow pointing to middle which is the promise queue.
<img width="642" alt="Screenshot 2023-03-22 at 3 17 05 PM" src="https://user-images.githubusercontent.com/12070823/227013109-335d7614-db07-4d91-974f-3c5cedffa724.png">

2023-03-22 19:22 UTC, DancingAxolotl commented on src/services/DomainService.ts
> +  const [domain, znsDomain] = await domainsBatchLoader.loadMany([
Yes, It's probably a good idea to use this throughout the repository if it gives significant performance improvements.

2023-03-22 19:23 UTC, DancingAxolotl commented on src/services/MetadataService.ts
> +        value: domain.children?.length || 0,
It's only loaded by the `DomainsService` which is only used by the metadata API.

2023-03-22 19:31 UTC, DancingAxolotl commented on src/controllers/StatusController.ts
> +    const lastUpdated = workerStatus?.updatedAt?.getTime() || 0;
We don't have much traffic here, but its latency is very bad and it drives our overall p99 up. We don't really need up to date block numbers here, we just need to know if the worker is stuck.

We can exclude this change for now and create a separate ticket to revisit it later.

2023-03-22 20:09 UTC, DancingAxolotl commented on src/services/DomainService.ts
> +    batchScheduleFn: setImmediate,
I don't like having a non-zero timeout because it sets a minimum latency for our requests. So when we don't have spikes of traffic, one request would have to wait for 100ms to complete just because it's the minimum timeout.
The idea is that it will wait for all pending requests to come in and execute everything that we have collected so far without adding any extra latency. 

I'm pretty sure the default implementation of `dataloader` would achieve it too, but it uses `process.nextTick` under the hood and it may have some [unexpected side-effects](https://nodejs.org/ru/docs/guides/event-loop-timers-and-nexttick#why-would-that-be-allowed).

2023-03-22 21:05 UTC, tunguyennnnn commented on src/services/DomainService.ts
> +    batchScheduleFn: setImmediate,
>So when we don't have spikes of traffic, one request would have to wait for 100ms to complete just because it's the minimum timeout
make sense but I am curious how pending requests will be pushed to the batch queue. can you let me know the query log when you run it on staging please 🙏

2023-03-23 17:46 UTC, tirish commented on src/services/MetadataService.ts
> +        value: domain.children?.length || 0,
Do we really need a fully hydrated list, though?

2023-03-24 10:44 UTC, DancingAxolotl commented on src/controllers/StatusController.ts
> +    const lastUpdated = workerStatus?.updatedAt?.getTime() || 0;
Discussed it with @sammyluo . We can keep this approach for now as there aren't any updates to the worker status table coming up. I created a linear ticket to reconsider this approach in the future.
https://linear.app/unstoppable-domains/issue/DT-1168/resolution-service-reconsider-status-endpoint

2023-03-24 12:18 UTC, DancingAxolotl commented on src/services/MetadataService.ts
> +        value: domain.children?.length || 0,
You are right, we don't really need it here. But it's better than doing a separate `count` query like we did before. It just adds a join to the existing query which doesn't add much latency.

2023-03-24 12:26 UTC, DancingAxolotl commented on src/services/DomainService.ts
> +  const [domain, znsDomain] = await domainsBatchLoader.loadMany([
I changed the `/domains/:domainName` endpoint to also use the `DomainService` with batched queries too. I think it should give a similar performance improvement.

I wanted to try adding batching to the repository itself, but one big issue that I ran into is that most of our queries are not easy to batch. 
Even for simple queries like `get domain by name` there could be different parameters (`relations` is the most common one) that prevent these queries from being batched easily. So we either need to have generic batch queries which fetch everything (similar to what we have here) or setup separate loaders for each possible query option.

So it's not going to be easy to set this up.

2023-03-24 12:27 UTC, DancingAxolotl commented on src/services/DomainService.ts
> +    batchScheduleFn: setImmediate,
I added a simple stats library to count average, min and max batch size. It will be available in the `_status` endpoint.
We can use it for testing and remove it before pushing to prod.

2023-03-28 15:00 UTC, tunguyennnnn approved these changes

2023-03-28 17:51 UTC, DancingAxolotl commented on src/controllers/StatusController.ts
> +    const lastUpdated = workerStatus?.updatedAt?.getTime() || 0;
I found another problem with this approach, it breaks the ZIL worker status because it turns out the status is not updated on each worker cycle. So for ZIL which has very rare transactions, the status updates rarely too and it's always out of sync. 

I moved these changes to a different PR so we can address them later #328

2023-03-30 13:42 UTC, DancingAxolotl commented on package.json
> +    "batchloader": "^0.0.22",
I did some experimenting. And for some reason `batchloader` is more stable than `dataloader`. Ultimately it provides similar performance improvements, but `batchloader` is ~20% better.
So I'm not really sure which one is better.

2023-04-03 17:38 UTC, DancingAxolotl commented on package.json
> +    "batchloader": "^0.0.22",
I ended up going with the batch loader library as it is easier to use and more stable based on the load testing. The way it's implemented it will be fairly easy to replace the library in the future if we need to.

2023-04-03 18:07 UTC, tunguyennnnn commented on src/api.ts
> +    batchingStats: batchingStats,
nit: 
```suggestion
    batchingStats,
```

2023-04-03 18:09 UTC, tunguyennnnn commented on src/models/Domain.ts
> +      relations: relations,
```suggestion
      relations,
```

2023-04-03 18:11 UTC, tunguyennnnn commented on src/services/DomainService.ts
> +  {
maybe later if we want to optimize more, batch load should have a cache interface we can use

2023-04-03 18:12 UTC, tunguyennnnn approved these changes
very nice!!!

2023-04-04 11:46 UTC, merged