[DT 1163] Fix to not fetch animal profile first
unstoppabledomains/resolution-service pull request #309
Opened 2023-03-20 15:03 UTC by tunguyennnnn

## Background

[Linear](https://linear.app/unstoppable-domains/issue/DT-1163/[bug]-animal-domain-thumbnail-overruling-profile-image-set-by-domain)
For animal domains, the animal image is returned by the resolution service first even if the domain owner has set a custom profile image. 

## Changes

* Fix imageUrl returned from metadata 
* Prioritize return on chain and off chain images over animal image for image-src
* increase timeout for fetching off-chain profile image

## To Do

## Additional Deployment and/or Rollback Steps

## Code Review

This Pull Request was thoroughly reviewed and meets all Code Review Standards pertaining to:

- [ ] **Implementation** - satisfied acceptance criteria
- [ ] **Communication** - notified engineers/stakeholders about impactful changes
- [ ] **Error handling** - handled, logged & alerted on errors
- [ ] **Documentation** - wrote readable code & commits, documented unintuitive code
- [ ] **Testing** - unit & E2E test coverage, tested in staging, DB migrations backwards compatible
- [ ] **Security** - sanitized inputs, vetted dependencies, validated/secured API requests, no committed secrets
- [ ] **Performance** - optimized expensive algorithms & database queries

Please select all **applied** standards relevant to this PR.
## Confirmation

- [ ] **Assignee Confirmation** - I (the author) have filled out the template above
- [ ] **Reviewer Confirmation** - I (a/the reviewer) confirm 1) the author has filled out the template and checked the box that says **Assignee Confirmation** 2) I reviewed the code and selected all applicable items in the code review section.

2023-03-21 19:54 UTC, sammyluo approved these changes
LGTM

2023-03-21 19:59 UTC, sammyluo requested changes

2023-03-21 19:59 UTC, sammyluo commented on src/utils/AnimalDomainHelper/AnimalDomainHelper.ts
> -        if (AnimalsDictionary.defaultAnimals.includes(animal)) {
Sorry, why is this code getting deleted?

2023-03-22 00:13 UTC, tunguyennnnn commented on src/utils/AnimalDomainHelper/AnimalDomainHelper.ts
> -        if (AnimalsDictionary.defaultAnimals.includes(animal)) {
those `defaultAnimals` are the ones that cause metadata to return a direct link from google cloud storage instead of image-src for `rabidgiraffe22.nft`

2023-03-28 02:22 UTC, sammyluo approved these changes
LGTM!

2023-03-28 02:37 UTC, sammyluo commented on src/controllers/MetaDataController.ts
> +      ? this.metadataService.createDefaultImageUrl(domain.name)
Why don't we always return the default image url and let the /image and /image-src endpoint to figure out what images they need to return? These image endpoints are grabbing offline images anyways, and we don't have to check offline images in /metadata endpoint.

2023-03-28 15:48 UTC, merged