[WIP] [DT-1188] feat: store domain records in a table instead of json blob
unstoppabledomains/resolution-service pull request #340
Opened 2023-04-13 21:24 UTC by DancingAxolotl

## Background

Looking up domains by records and accessing specific records is slow since they are stored in a json blob within postgres. This PR changes storage to a separate table in the DB.

## Changes

 - Added a new table for domain resolution records
 - Updated workers to save records to the new table
 - Updated API controllers to read from the new table

## To Do

 - [ ] Re-write/fix unit tests
 - [ ] Deprecate the old json blob
 - [ ] Some more testing + load testing on testnets
 - [ ] Make sure that backfilling records works, possibly move to a script instead of a migration for backfilling the records table

## Code Review

This Pull Request was thoroughly reviewed and meets all Code Review Standards pertaining to:

- [ ] **Implementation** - satisfied acceptance criteria
- [ ] **Communication** - notified engineers/stakeholders about impactful changes
- [ ] **Error handling** - handled, logged & alerted on errors
- [ ] **Documentation** - wrote readable code & commits, documented unintuitive code
- [ ] **Testing** - unit & E2E test coverage, tested in staging, DB migrations backwards compatible
- [ ] **Security** - sanitized inputs, vetted dependencies, validated/secured API requests, no committed secrets
- [ ] **Performance** - optimized expensive algorithms & database queries

Please select all **applied** standards relevant to this PR.
## Confirmation

- [ ] **Assignee Confirmation** - I (the author) have filled out the template above
- [ ] **Reviewer Confirmation** - I (a/the reviewer) confirm 1) the author has filled out the template and checked the box that says **Assignee Confirmation** 2) I reviewed the code and selected all applicable items in the code review section.

2023-04-14 11:04 UTC, DancingAxolotl reviewed
Left some notes inline for future implementation

2023-04-14 11:04 UTC, DancingAxolotl commented on src/models/DomainsResolutionRecords.ts
> +  // })
We have the option to validate records with regexes in the `resolver-keys.json` but as you would expect we have lots of records on-chain which don't match our regexes. Adding this validation will make these records invalid. This could be a good thing - avoids sending crypto to invalid addresses; and a bad thing - breaks a bunch of existing records. We should think about this.

2023-04-14 11:04 UTC, DancingAxolotl commented on src/workers/framework/WorkerRepository.ts
> +        }
Untested

2023-05-03 17:29 UTC, DancingAxolotl commented on src/models/DomainsResolutionRecords.ts
> +  // })
For now I am removing this validation. After thinking about it, it introduces a lot more problems than it solves.

There is no way for us to control which records are placed on-chain, so there will always be invalid/broken records. Since the goal of the resolution service is to mirror the state of the blockchain, it has to return these records as is. Regardless if they match any of our conventional formats.

2023-05-08 15:20 UTC, tunguyennnnn requested changes
migration will take very long and the code relying on the new table. 
I think we need to make it into either:
* deploying a separate PR that populate the new table, and worker starts to write both to new table and the old json blob. -> backfill the table -> deploy the code that reads from the new table
OR 
* having bridge code, it should lookup into the new table and fallback to old json blob if no record is found.

2023-05-08 18:01 UTC, tunguyennnnn commented on src/controllers/DomainsController.ts
> +            ? resolution.records.filter((kv) => query.key == kv.key)
```suggestion
            ? resolution.records.filter((kv) => query.key === kv.key)
```

2023-05-10 10:59 UTC, DancingAxolotl commented on src/controllers/DomainsController.ts
> +      response.records = resolution.records.reduce((records, record) => {
Yes, the value column could be empty. For some reason we have some empty resolutions in the DB already. And theoretically you can set a bunch of empty records in the smart contract. So just to clean up the response I'm not returning them in the final json.

2023-05-10 17:08 UTC, DancingAxolotl commented
I pulled some changes from #353 into this PR to have everything implementation-related here. So only unit test fixes are left in #353 

> migration will take very long and the code relying on the new table.
> I think we need to make it into either:
> deploying a separate PR that populate the new table, and worker starts to write both to new table and the old json blob. -> backfill the table -> deploy the code that reads from the new table

@tunguyennnnn Yes, that is the plan for now.

2023-05-10 17:21 UTC, tunguyennnnn approved these changes
LGTM!

2023-05-11 14:10 UTC, DancingAxolotl commented
<img width="1167" alt="Screenshot 2023-05-11 at 15 08 57" src="https://github.com/unstoppabledomains/resolution-service/assets/5020980/3f266268-d52a-4dab-90c7-9f3799e9f588">

2023-05-12 01:12 UTC, merged