[DT 1459] Naming service controller and get domain
unstoppabledomains/resolution-service pull request #381
Opened 2023-07-26 15:35 UTC by tunguyennnnn

## Background

Refactor to have multiple blockchain + naming services 

## Changes
* Add new naming service controller class
* Apply the new naming service controller to get domains/:domain controller

## To Do

## Additional Deployment and/or Rollback Steps

## Code Review

This Pull Request was thoroughly reviewed and meets all Code Review Standards pertaining to:

- [ ] **Implementation** - satisfied acceptance criteria
- [ ] **Communication** - notified engineers/stakeholders about impactful changes
- [ ] **Error handling** - handled, logged & alerted on errors
- [ ] **Documentation** - wrote readable code & commits, documented unintuitive code
- [ ] **Testing** - unit & E2E test coverage, tested in staging, DB migrations backwards compatible
- [ ] **Security** - sanitized inputs, vetted dependencies, validated/secured API requests, no committed secrets
- [ ] **Performance** - optimized expensive algorithms & database queries

Please select all **applied** standards relevant to this PR.
## Confirmation

- [ ] **Assignee Confirmation** - I (the author) have filled out the template above
- [ ] **Reviewer Confirmation** - I (a/the reviewer) confirm 1) the author has filled out the template and checked the box that says **Assignee Confirmation** 2) I reviewed the code and selected all applicable items in the code review section.

2023-07-26 20:16 UTC, sammyluo requested changes
Nice refactoring! Great start! 🙌 Just left some minor questions and change requests.

2023-07-26 20:16 UTC, sammyluo commented on src/services/nameing-services/EnsNamingService.ts
> +resolutionRecordsToKeyValue;
?

2023-07-26 20:31 UTC, tunguyennnnn commented on src/utils/evmUtils.ts
> +  return address === null || address === NullAddress;
I think that would be useful for another function but i've seen use case for it, but need a different function signature:
```
export const isEthNullAddress = (address: string): boolean =>
```

2023-07-26 20:33 UTC, tunguyennnnn commented on src/middleware/inputValidators/validateDomainNameQuery.ts
> +      throw new InvalidInputError('Unsupported TLD');
i think this should be job of middleware and controller to throw custom Error
the `InvalidInputError` is a custom http error with code, getNamingServiceForDomain concern should only care if there's a service to handle it

2023-07-26 20:39 UTC, tunguyennnnn commented on src/services/nameing-services/UdNamingService.ts
> +  protected buildDomainResponse(
yea agree! I was thinking of another custom return type in `GetDomainResponse` 
The reason why we may not return `Domain` is if we have API proxy for another naming service, it doesn't fit into `Domain` model
Let's figure out when we reach to that point though, for now all namingservice return the same thing

2023-07-26 20:44 UTC, tunguyennnnn commented on src/middleware/InputValidatorsMiddleware.test.ts
> +      expect(mockResponse.locals.namingService instanceof ZilNamingService).to
yea this should not have any naming service 😄

2023-07-26 20:45 UTC, tunguyennnnn commented on src/services/nameing-services/index.ts
> +    return null;
yea lets the controller + middleware throw and decide what error is it instead

2023-07-26 20:46 UTC, tunguyennnnn commented on src/services/nameing-services/EnsNamingService.ts
> +resolutionRecordsToKeyValue;
🔪

2023-07-26 20:55 UTC, tunguyennnnn commented on src/middleware/InputValidatorsMiddleware.test.ts
> +      expect(mockResponse.locals.namingService instanceof ZilNamingService).to
FYI, for tokenId we cannot determine naming service by domain name, so i defer this to MetadataController to handle which naming service to handle

2023-07-27 18:23 UTC, sammyluo approved these changes
LGTM! 🚀 ⭐

2023-07-27 18:23 UTC, sammyluo commented on src/services/nameing-services/ZilNamingService.ts
> +    const udNameHash = this.getNameHash(domainName);
Nit: 
```suggestion
    const unsNameHash = this.getNameHash(domainName);
```

2023-07-27 20:10 UTC, DancingAxolotl approved these changes
Great work! One minor comment, otherwise LGTM 🙌 🚀

2023-07-27 20:19 UTC, tunguyennnnn commented on src/services/nameing-services/BaseNamingService.ts
> +  }
ah yea they are abstract methods too for controller 😁

2023-07-27 20:26 UTC, tunguyennnnn commented on src/services/nameing-services/BaseNamingService.ts
> +  }
ah yea  for `getDomainByName`
the `getDomainFromTokenId` is not implemented by Uns naming service yet so I'd leave it to return null for now

2023-07-31 14:39 UTC, merged