Refactoring metadata response
unstoppabledomains/resolution-service pull request #72
Opened 2022-02-23 14:41 UTC by refats

2022-02-24 15:09 UTC, refats commented
https://www.pivotaltracker.com/n/projects/2465324/stories/180411972
refactored unit tests for new attributes
changed metaData response, deleted image_data field from OpenSeaMetadata
added basic attributed with domain ending and name length
also new attribute added for blockchain resolution if it's possible.

2022-02-24 16:40 UTC, DancingAxolotl requested changes
@refats Good work!
I've left a few minor comments. And I'd like to discuss the domain attributes for animal and premium domains. But other than that the PR looks good.

2022-02-24 16:40 UTC, DancingAxolotl commented on src/controllers/MetaDataController.ts
> -    }
I think we should keep animal and premium attributes. Animal domains have custom domain images, so I think it would be appropriate to keep the domain type and animal type for these domains. Let's discuss it with the team later.

2022-02-24 16:40 UTC, DancingAxolotl commented on src/controllers/MetaDataController.ts
> +    attributes.push({ trait_type: 'chain', value: resolution.blockchain });
Maybe let's change `getBasicDomainAttributes(name: string)` to `getBasicDomainAttributes(domain: Domain)` and get the blockchain data there?

2022-02-24 16:40 UTC, DancingAxolotl commented on src/controllers/MetaDataController.ts
>          value: punycode.toUnicode(name).split('.')[0].length,
It's better to use `domain.extension` and `domain.label` instead of splitting the name manually

2022-02-24 16:40 UTC, DancingAxolotl commented on src/controllers/MetaDataController.ts
>          value: punycode.toUnicode(name).split('.')[0].length,
It's better to use `domain.extension` and `domain.label` instead of splitting the name manually

2022-02-24 16:40 UTC, DancingAxolotl requested changes
@refats Good work!
I've left a few minor comments. And I'd like to discuss the domain attributes for animal and premium domains. But other than that the PR looks good.

2022-02-24 16:47 UTC, refats commented on src/controllers/MetaDataController.ts
> +    attributes.push({ trait_type: 'chain', value: resolution.blockchain });
Yes, I can move part of getting resolution of domain here, if domain is valid.
But this need to change upper function defaultMetaResponse to provide Domain type instead the name.
No problem

2022-02-24 16:50 UTC, refats commented on src/controllers/MetaDataController.ts
>          value: punycode.toUnicode(name).split('.')[0].length,
for example for test with unknown.crypto defaultMetaResponse couldn't create Domain object, so just parse the string name of provided input.

2022-08-18 14:33 UTC, DancingAxolotl commented
@sammyluo I think it should be okay to close this as stale.

2022-09-12 19:26 UTC, closed without merging